import os

OPEN_WEATHER_API_KEY = os.getenv('OPEN_WEATHER_API_KEY')
print(OPEN_WEATHER_API_KEY)
print("AAAAAAAAAAAAAAAAAAAAAAAAA")
REQUEST_LIMIT = 60
TIME_WINDOW = 60
CITIES = [3439525, 3439781, 3440645]


def run_config(app):
    app.config['OPEN_WEATHER_API_KEY'] = OPEN_WEATHER_API_KEY
